### ISSUE TITLE
Filed to install libndk

### ISSUE THREAD

**Issue by Lepplex** [casualsnek/waydroid_script#104]
(vg13X) pc@pc-HP-Laptop-15s-fq1xxx:~/python/bin$ sudo /home/pc/vg13X/bin/python3 /home/pc/waydroid_script/main.py install libndk
INFO: Downloading libndktranslation.zip now to /home/pc/.cache/waydroid-script/downloads/libndktranslation.zip .....
INFO: Extracting /home/pc/.cache/waydroid-script/downloads/libndktranslation.zip to /tmp/libndkunpack
INFO: Copying libndk library files ...
Traceback (most recent call last):
  File "/home/pc/waydroid_script/main.py", line 343, in <module>
    main()
  File "/home/pc/waydroid_script/main.py", line 336, in main
    args.func(args)
  File "/home/pcwaydroid_script/main.py", line 107, in install_app
    item.install()
  File "/home/pc/waydroid_script/stuff/general.py", line 180, in install
    self.add_props()
  File "/home/pc/waydroid_script/stuff/general.py", line 76, in add_props
    shutil.copy(os.path.join(
  File "/usr/lib/python3.11/shutil.py", line 419, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.11/shutil.py", line 256, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './bin/x86_64/resetprop'
(vg13X) pc@pc-HP-Laptop-15s-fq1xxx:~/python/bin$ 

Any ideas?

**Comment by Lepplex** [comment]
I'm on Ubuntu 23.04
(it's not crossed out in my terminal)

**Comment by ayasa520** [comment]
https://github.com/ayasa520/waydroid_script/commit/a45737aca868042f7e72f740605e165103129588

**Comment by steviator** [comment]
Both Houdini and Libndk are broken because files are missing from the archives that Waydroid-extras downloads. 

These scripts are basically junk now, nobody is testing or fixing them apparently.

**Comment by ayasa520** [comment]
> Both Houdini and Libndk are broken because files are missing from the archives that Waydroid-extras downloads.
> 
> These scripts are basically junk now, nobody is testing or fixing them apparently.
Are you blind? 
![image](https://github.com/casualsnek/waydroid_script/assets/55699692/f249d2d1-4a84-4914-8f68-e9c850e84b57)

**Comment by ayasa520** [comment]
> Both Houdini and Libndk are broken because files are missing from the archives that Waydroid-extras downloads.
> 
> These scripts are basically junk now, nobody is testing or fixing them apparently.


![image](https://github.com/casualsnek/waydroid_script/assets/55699692/4f5d8d3c-a432-469a-bf47-54387a62b99f)
I just haven't created a PR yet. How blind you are.
