### ISSUE TITLE
Minor Assistance Needed

### ISSUE THREAD

**Issue by 641i130** [casualsnek/waydroid_script#108]
```python
? Select Android version Android 11
? Please select an action Install
? Select apps ['gapps', 'libndk']
INFO: Downloading gapps.zip now to /home/walnut/.cache/waydroid-script/downloads/gapps.zip .....
INFO: Extracting /home/walnut/.cache/waydroid-script/downloads/gapps.zip to /tmp/gapps/extract
    Processing app package : /tmp/gapps/extract/Core/vending-x86_64.tar.lz
ERROR: tar (child): lzip: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

Traceback (most recent call last):
  File "main.py", line 343, in <module>
    main()
  File "main.py", line 339, in main
    interact()
  File "main.py", line 246, in interact
    install_app(args)
  File "main.py", line 107, in install_app
    item.install()
  File "/home/walnut/Downloads/waydroid_script/stuff/general.py", line 177, in install
    self.copy()
  File "/home/walnut/Downloads/waydroid_script/stuff/gapps.py", line 109, in copy
    return self.copy_11()
  File "/home/walnut/Downloads/waydroid_script/stuff/gapps.py", line 126, in copy_11
    run(["tar", "--lzip", "-xvf", os.path.join(self.extract_to, "Core",
  File "/home/walnut/Downloads/waydroid_script/tools/helper.py", line 47, in run
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['tar', '--lzip', '-xvf', '/tmp/gapps/extract/Core/vending-x86_64.tar.lz', '-C', '/tmp/gapps/extract/appunpack']' returned non-zero exit status 2.
```

**Comment by casualsnek** [comment]
Do you have lzip installed ? If not install lzip using your package manager and run the script again !

**Comment by 641i130** [comment]
Now this happens:
```
? Select Android version Android 11
? Please select an action Install
? Select apps ['gapps', 'libndk']
INFO: Downloading gapps.zip now to /home/walnut/.cache/waydroid-script/downloads/gapps.zip .....
INFO: Extracting /home/walnut/.cache/waydroid-script/downloads/gapps.zip to /tmp/gapps/extract
    Processing app package : /tmp/gapps/extract/Core/vending-x86_64.tar.lz
    Processing extra package : /tmp/gapps/extract/Core/vending-common.tar.lz
    Processing app package : /tmp/gapps/extract/Core/gsfcore-all.tar.lz
    Processing app package : /tmp/gapps/extract/Core/googlepartnersetup-all.tar.lz
    Processing app package : /tmp/gapps/extract/Core/googleonetimeinitializer-all.tar.lz
    Processing app package : /tmp/gapps/extract/Core/googlefeedback-all.tar.lz
    Processing app package : /tmp/gapps/extract/Core/googlecontactssync-all.tar.lz
    Processing app package : /tmp/gapps/extract/Core/googlebackuptransport-all.tar.lz
    Processing app package : /tmp/gapps/extract/Core/gmscore-x86_64.tar.lz
    Processing app package : /tmp/gapps/extract/Core/extsharedgoogle-all.tar.lz
    Processing app package : /tmp/gapps/extract/Core/extservicesgoogle-all.tar.lz
    Processing extra package : /tmp/gapps/extract/Core/defaultframework-common.tar.lz
    Processing extra package : /tmp/gapps/extract/Core/defaultetc-common.tar.lz
    Processing app package : /tmp/gapps/extract/Core/datatransfertool-all.tar.lz
    Processing app package : /tmp/gapps/extract/Core/configupdater-all.tar.lz
    Processing app package : /tmp/gapps/extract/Core/carriersetup-all.tar.lz
    Processing app package : /tmp/gapps/extract/Core/backuprestore-all.tar.lz
INFO: OpenGapps installation finished
INFO: Downloading libndktranslation.zip now to /home/walnut/.cache/waydroid-script/downloads/libndktranslation.zip .....
INFO: Extracting /home/walnut/.cache/waydroid-script/downloads/libndktranslation.zip to /tmp/libndkunpack
INFO: Copying libndk library files ...
INFO: libndk installation finished
ERROR: Traceback (most recent call last):
  File "/usr/bin/waydroid", line 6, in <module>
    import tools
  File "/usr/lib/waydroid/tools/__init__.py", line 12, in <module>
    from . import actions
  File "/usr/lib/waydroid/tools/actions/__init__.py", line 3, in <module>
    from tools.actions.initializer import init, wait_for_init, remote_init_client
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 5, in <module>
    from tools import helpers
  File "/usr/lib/waydroid/tools/helpers/__init__.py", line 5, in <module>
    import tools.helpers.props
  File "/usr/lib/waydroid/tools/helpers/props.py", line 8, in <module>
    from tools.interfaces import IPlatform
  File "/usr/lib/waydroid/tools/interfaces/IPlatform.py", line 1, in <module>
    import gbinder
ModuleNotFoundError: No module named 'gbinder'

Traceback (most recent call last):
  File "main.py", line 343, in <module>
    main()
  File "main.py", line 339, in main
    interact()
  File "main.py", line 246, in interact
    install_app(args)
  File "main.py", line 113, in install_app
    container.upgrade()
  File "/home/walnut/Downloads/waydroid_script/tools/container.py", line 53, in upgrade
    run(["waydroid", "upgrade", "-o"], ignore=r"\[.*\] Stopping container\n\[.*\] Starting container")
  File "/home/walnut/Downloads/waydroid_script/tools/helper.py", line 47, in run
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['waydroid', 'upgrade', '-o']' returned non-zero exit status 1.
```

**Comment by ayasa520** [comment]
> ModuleNotFoundError: No module named 'gbinder'

How is that possible,  waydroid won't even work without gbinder. Please make sure that waydroid script and waydroid use the same python interpreter.

**Comment by 641i130** [comment]
Turns out I was missing a few things with python and conda... Sorry! 

Trying out openrc ... It is very painful lol
