### ISSUE TITLE
Unable to Install Other MinMicroG Variants (i.e., MinMicroG Minimal)

### ISSUE THREAD

**Issue by ryanbarillos** [casualsnek/waydroid_script#135]
I've been trying to install MicroG Minimal as I prefer not installing the Standard.

However every time I do so returns a Python error, which I can't solve (I'm not experienced in that programming language yet).
I've uninstalled Waydroid just recently, so I can't do further tests on which other MicroG variants, but I can tell that MinMicroG Minimal is most affected, as I can't install it.

**Comment by ryanbarillos** [comment]
New year, and I got to reinstall Waydroid again.

Some following system information:

System: Arch Linux (Vanilla)
Waydroid Install Method: `yay -Sa --removemake --cleanafter waydroid && sudo waydroid init`

Here's the output:
```
? Select Android version Android 11
? Please select an action Install
? Select apps ['microg']
? Select MicroG variant Minimal
Traceback (most recent call last):
  File "/home/user/waydroid_script/main.py", line 358, in <module>
    main()
  File "/home/user/waydroid_script/main.py", line 354, in main
    interact()
  File "/home/user/waydroid_script/main.py", line 256, in interact
    install_app(args)
  File "/home/user/waydroid_script/main.py", line 87, in install_app
    install_list.append(MicroG(args.android_version, args.microg_variant))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/waydroid_script/stuff/microg.py", line 109, in __init__
    self.act_md5 = self.dl_links[variant][1]
                   ~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by Hash6232** [comment]
Still getting this error when attempting to install the minimal version. I just cloned the repo so I'm fairly sure to be using an up to date version

```
Traceback (most recent call last):
  File "/home/user/.local/share/repo/waydroid_script/main.py", line 358, in <module>
    main()
  File "/home/user/.local/share/repo/waydroid_script/main.py", line 354, in main
    interact()
  File "/home/user/.local/share/repo/waydroid_script/main.py", line 256, in interact
    install_app(args)
  File "/home/user/.local/share/repo/waydroid_script/main.py", line 87, in install_app
    install_list.append(MicroG(args.android_version, args.microg_variant))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/repo/waydroid_script/stuff/microg.py", line 109, in __init__
    self.act_md5 = self.dl_links[variant][1]
                   ~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by ryanbarillosofficial** [comment]
No. A for

> Still getting this error when attempting to install the minimal version. I just cloned the repo so I'm fairly sure to be using an up to date version
> 
> ```
> Traceback (most recent call last):
>   File "/home/user/.local/share/repo/waydroid_script/main.py", line 358, in <module>
>     main()
>   File "/home/user/.local/share/repo/waydroid_script/main.py", line 354, in main
>     interact()
>   File "/home/user/.local/share/repo/waydroid_script/main.py", line 256, in interact
>     install_app(args)
>   File "/home/user/.local/share/repo/waydroid_script/main.py", line 87, in install_app
>     install_list.append(MicroG(args.android_version, args.microg_variant))
>                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/.local/share/repo/waydroid_script/stuff/microg.py", line 109, in __init__
>     self.act_md5 = self.dl_links[variant][1]
>                    ~~~~~~~~~~~~~~~~~~~~~~^^^
> IndexError: list index out of range
> ```
> 
> I tried adding a print() before the line causing the out of index crash and this is the resulting array:
> 
> ```python
> ['https://github.com/ayasa520/MinMicroG/releases/download/latest/MinMicroG-Minimal-2.11.1-20230429100521.zipafb87eb64e7749cfd72c4760d85849da']
> ```
> 
> I think the link and md5 are being merged for some reason instead of being split into two components
> 
> Yeah a comma is missing in the dl_links object. Manually adding the commas fixed the problem entirely
> 
> https://github.com/casualsnek/waydroid_script/blob/1a2d3ad643206ad5f040e0155bb7ab86c0430365/stuff/microg.py#L25-L46

No. Only a fork of this project merged the fix. But this one by the original author has not.
