### ISSUE TITLE
Error installing gapps in a clean install of waydroid.

### ISSUE THREAD

**Issue by kam92** [casualsnek/waydroid_script#136]
? Select Android version Android 11
? Please select an action Install
? Select apps ['gapps', 'libhoudini']

INFO: Downloading gapps.zip now to /home/user/.cache/waydroid-script/downloads/gapps.zip .....

INFO: Extracting /home/user/.cache/waydroid-script/downloads/gapps.zip to /tmp/gapps/extract
    Processing app package : /tmp/gapps/extract/Core/datatransfertool-all.tar.lz
ERROR: tar (child): lzip: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

Traceback (most recent call last):
  File "/home/user/waydroid_script/main.py", line 353, in <module>
    main()
  File "/home/user/waydroid_script/main.py", line 349, in main
    interact()
  File "/home/user/waydroid_script/main.py", line 251, in interact
    install_app(args)
  File "/home/user/waydroid_script/main.py", line 110, in install_app
    item.install()
  File "/home/user/waydroid_script/stuff/general.py", line 177, in install
    self.copy()
  File "/home/user/waydroid_script/stuff/gapps.py", line 109, in copy
    return self.copy_11()
  File "/home/user/waydroid_script/stuff/gapps.py", line 126, in copy_11
    run(["tar", "--lzip", "-xvf", os.path.join(self.extract_to, "Core",
  File "/home/user/waydroid_script/tools/helper.py", line 48, in run
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['tar', '--lzip', '-xvf', '/tmp/gapps/extract/Core/datatransfertool-all.tar.lz', '-C', '/tmp/gapps/extract/appunpack']' returned non-zero exit status 2.

**Comment by kam92** [comment]
Ubuntu 22.04 x64

**Comment by casualsnek** [comment]
> Ubuntu 22.04 x64

Looks like you have not installed lzip !
Can you run ``sudo apt install lzip`` and run the script again to see if it fixes the issue !
