### ISSUE TITLE
smartdock url is expired

### ISSUE THREAD

**Issue by dffxd-suntra** [casualsnek/waydroid_script#163]
can not request https://f-droid.org/repo/cu.axel.smartdock_1100.apk

**Comment by FrostNovaHD** [comment]
https://github.com/casualsnek/waydroid_script/pull/161

**Comment by EliasTheGrandMasterOfMistakes** [comment]
#165

**Comment by EliasTheGrandMasterOfMistakes** [comment]
> #161

if you want you can just cherry pick my last commit this fixes permissions

**Comment by EliasTheGrandMasterOfMistakes** [comment]
https://github.com/casualsnek/waydroid_script/pull/165/commits/22c8e20fceaefc0d8e1969220b2d207916ed0359

**Comment by EliasTheGrandMasterOfMistakes** [comment]
sadly i had found a problem in this new version, that is.
crash when using multi.windows mod

**Comment by hawari21** [comment]
Sorry i am a begginer here, but how can i apply the fix inside "FIles changes" tab?

**Comment by The-MAZZTer** [comment]
I tried to apply the fix which appeared successful, but once smartdock is installed waydroid no longer boots and gets stuck on the boot animation.

Could be a Steam Deck specific problem. I didn't look too closely at it.

**Comment by AClon314** [comment]
> I tried to apply the fix which appeared successful, but once smartdock is installed waydroid no longer boots and gets stuck on the boot animation.
> 
> Could be a Steam Deck specific problem. I didn't look too closely at it.

Not only in Steam Deck, but also on my weston waydroid, with latest smartdesk v1.12.1 on f-droid. (I've modified smartdock.py `dl_link` & `act_md5`)

Same stuck at boot up animation running in cycle repeatedly.

**Comment by dgudim** [comment]
Same here, installing smartdock from fdroid works, but I couldn't hide the native navigation bar

**Comment by dgudim** [comment]
```
Process: system_server
Build: waydroid/lineage_waydroid_x86_64/waydroid_x86_64:11/RQ3A.211001.001/83:userdebug/test-keys

java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions whitelist: {cu.axel.smartdock (/system/priv-app/SmartDock): android.permission.WRITE_SECURE_SETTINGS}
	at com.android.server.pm.permission.PermissionManagerService.systemReady(PermissionManagerService.java:4756)
	at com.android.server.pm.permission.PermissionManagerService.access$500(PermissionManagerService.java:178)
	at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.systemReady(PermissionManagerService.java:4839)
	at com.android.server.pm.PackageManagerService.systemReady(PackageManagerService.java:21834)
	at com.android.server.SystemServer.startOtherServices(SystemServer.java:2210)
	at com.android.server.SystemServer.run(SystemServer.java:601)
	at com.android.server.SystemServer.main(SystemServer.java:417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:926)
```
