### ISSUE TITLE
Unable to install apps because of python issue.

### ISSUE THREAD

**Issue by lDEVinux** [casualsnek/waydroid_script#181]
I was trying to install gapps on waydroid but it just keeps crashing with this:
`? Select Android version Android 11
? Please select an action Install
? Select apps ['gapps']
INFO: Downloading gapps.zip now to /home/void4dev/.cache/waydroid-script/downloads/gapps.zip .....
INFO: Extracting /home/void4dev/.cache/waydroid-script/downloads/gapps.zip to /tmp/gapps/extract
    Processing app package : /tmp/gapps/extract/Core/backuprestore-all.tar.lz
ERROR: tar (child): lzip: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

Traceback (most recent call last):
  File "/home/void4dev/waydroid_script/main.py", line 358, in <module>
    main()
  File "/home/void4dev/waydroid_script/main.py", line 354, in main
    interact()
  File "/home/void4dev/waydroid_script/main.py", line 256, in interact
    install_app(args)
  File "/home/void4dev/waydroid_script/main.py", line 113, in install_app
    item.install()
  File "/home/void4dev/waydroid_script/stuff/general.py", line 177, in install
    self.copy()
  File "/home/void4dev/waydroid_script/stuff/gapps.py", line 109, in copy
    return self.copy_11()
           ^^^^^^^^^^^^^^
  File "/home/void4dev/waydroid_script/stuff/gapps.py", line 126, in copy_11
    run(["tar", "--lzip", "-xvf", os.path.join(self.extract_to, "Core",
  File "/home/void4dev/waydroid_script/tools/helper.py", line 48, in run
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['tar', '--lzip', '-xvf', '/tmp/gapps/extract/Core/backuprestore-all.tar.lz', '-C', '/tmp/gapps/extract/appunpack']' returned non-zero exit status 2.
`

**Comment by lDEVinux** [comment]
Sorry, it was a issue on my part, lzip wasn't installed
