### ISSUE TITLE
Cannot install GAPPS, e2fsck: Cannot continue, aborting.

### ISSUE THREAD

**Issue by asdfghjkl403622** [casualsnek/waydroid_script#182]
`waydroid_script]$ sudo venv/bin/python3 main.py install gapps
INFO: Resizing /var/lib/waydroid/images/system.img to 2664M
ERROR: e2fsck 1.47.1 (20-May-2024)
e2fsck: Cannot continue, aborting.

Traceback (most recent call last):
  File "/home/samy/gitthings/waydroid_script/main.py", line 358, in <module>
    main()
  File "/home/samy/gitthings/waydroid_script/main.py", line 351, in main
    args.func(args)
  File "/home/samy/gitthings/waydroid_script/main.py", line 105, in install_app
    resize("system")
  File "/home/samy/gitthings/waydroid_script/main.py", line 50, in resize
    images.resize(img, new_size)
  File "/home/samy/gitthings/waydroid_script/tools/images.py", line 27, in resize
    run(["sudo", "e2fsck", "-y", "-f", img_file], ignore="^e2fsck \d+\.\d+\.\d (.+)\n$")
/home/samy/gitthings/waydroid_script/tools/images.py:1: SyntaxWarning: invalid escape sequence '\d'
  import configparser
  File "/home/samy/gitthings/waydroid_script/tools/helper.py", line 48, in run
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['sudo', 'e2fsck', '-y', '-f', '/var/lib/waydroid/images/system.img']' returned non-zero exit status 8.`

archlinux

**Comment by YogSottot** [comment]
Your ```system.img``` is probably corrupted. Try re-downloading it.

**Comment by jkoehler11** [comment]
I am also experiencing this issue with the latest from `main`. I redownloaded the image with `waydroid init -s GAPPS -f` and the issue still persists.

```
sudo venv/bin/python3 main.py install libndk
INFO: Resizing /var/lib/waydroid/images/system.img to 2840M
ERROR: e2fsck 1.47.1 (20-May-2024)
e2fsck: Cannot continue, aborting.



Traceback (most recent call last):
  File "/home/james/waydroid_script/main.py", line 358, in <module>
    main()
  File "/home/james/waydroid_script/main.py", line 351, in main
    args.func(args)
  File "/home/james/waydroid_script/main.py", line 105, in install_app
    resize("system")
  File "/home/james/waydroid_script/main.py", line 50, in resize
    images.resize(img, new_size)
  File "/home/james/waydroid_script/tools/images.py", line 27, in resize
    run(["sudo", "e2fsck", "-y", "-f", img_file], ignore="^e2fsck \d+\.\d+\.\d (.+)\n$")
/home/james/waydroid_script/tools/images.py:1: SyntaxWarning: invalid escape sequence '\d'
  import configparser
  File "/home/james/waydroid_script/tools/helper.py", line 48, in run
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['sudo', 'e2fsck', '-y', '-f', '/var/lib/waydroid/images/system.img']' returned non-zero exit status 8.
```

**Comment by jkoehler11** [comment]
Manually running the command:

```
sudo e2fsck -y -f /var/lib/waydroid/images/system.img
e2fsck 1.47.1 (20-May-2024)
/var/lib/waydroid/images/system.img is mounted.



WARNING!!!  The filesystem is mounted.   If you continue you ***WILL***
cause ***SEVERE*** filesystem damage.


Do you really want to continue<n>? no
check aborted.
```

I stopped the container: `sudo systemctl stop waydroid-container.service`

and re-ran the command `sudo systemctl stop waydroid-container.service` which succeeded this time:

`e2fsck 1.47.1 (20-May-2024)
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
/: 4703/152608 files (0.4% non-contiguous), 472502/599040 blocks`

Then running the install command again gives this error:

`sudo venv/bin/python3 main.py install libndk
INFO: Resizing /var/lib/waydroid/images/system.img to 2840M
INFO: Mounting /var/lib/waydroid/images/system.img to /tmp/waydroid
WARN: /tmp/waydroid is not a mount point
ERROR: mount: /tmp/waydroid: wrong fs type, bad option, bad superblock on /dev/loop0, missing codepage or helper program, or other error.
       dmesg(1) may have more information after failed mount system call.

Traceback (most recent call last):
  File "/home/james/waydroid_script/main.py", line 358, in <module>
    main()
  File "/home/james/waydroid_script/main.py", line 351, in main
    args.func(args)
  File "/home/james/waydroid_script/main.py", line 109, in install_app
    mount("system", copy_dir)
  File "/home/james/waydroid_script/main.py", line 42, in mount
    images.mount(img, mount_point)
  File "/home/james/waydroid_script/tools/images.py", line 12, in mount
    run(["mount", "-o", "rw", image, mount_point])
  File "/home/james/waydroid_script/tools/helper.py", line 48, in run
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['mount', '-o', 'rw', '/var/lib/waydroid/images/system.img', '/tmp/waydroid']' returned non-zero exit status 32.`

**Comment by jkoehler11** [comment]
I restarted my computer and then opened up the waydroid container.

After that, I re-ran the command `sudo venv/bin/python3 main.py install libndk` and this time it worked:

`NFO: Resizing /var/lib/waydroid/images/system.img to 4340M
INFO: Mounting /var/lib/waydroid/images/system.img to /tmp/waydroid
INFO: Mounting /var/lib/waydroid/images/vendor.img to /tmp/waydroid/vendor
WARN: /tmp/waydroid/vendor is not a mount point
INFO: Downloading libndktranslation.zip now to /home/james/.cache/waydroid-script/downloads/libndktranslation.zip .....
INFO: Extracting /home/james/.cache/waydroid-script/downloads/libndktranslation.zip to /tmp/libndkunpack
INFO: Copying libndk library files ...
INFO: libndk installation finished
INFO: Umounting /tmp/waydroid/vendor
INFO: Umounting /tmp/waydroid`

**Comment by asdfghjkl403622** [comment]
after reinstalling the systemimg, I get this ? Select Android version Android 13
? Please select an action Install
? Select apps ['gapps']
INFO: Resizing /var/lib/waydroid/images/system.img to 2177M
INFO: Mounting /var/lib/waydroid/images/system.img to /tmp/waydroid
INFO: Mounting /var/lib/waydroid/images/vendor.img to /tmp/waydroid/vendor
WARN: /tmp/waydroid/vendor is not a mount point
INFO: Downloading gapps.zip now to /home/samy/.cache/waydroid-script/downloads/gapps.zip .....
WARN: md5 mismatches, redownloading now ....
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 198M/198M [00:02<00:00, 92.1MiB/s]
INFO: Extracting /home/samy/.cache/waydroid-script/downloads/gapps.zip to /tmp/gapps/extract
Traceback (most recent call last):
  File "/home/samy/gitthings/waydroid_script/main.py", line 358, in <module>
    main()
  File "/home/samy/gitthings/waydroid_script/main.py", line 354, in main
    interact()
  File "/home/samy/gitthings/waydroid_script/main.py", line 256, in interact
    install_app(args)
  File "/home/samy/gitthings/waydroid_script/main.py", line 113, in install_app
    item.install()
  File "/home/samy/gitthings/waydroid_script/stuff/general.py", line 177, in install
    self.copy()
  File "/home/samy/gitthings/waydroid_script/stuff/gapps.py", line 111, in copy
    return self.copy_13()
           ^^^^^^^^^^^^^^
  File "/home/samy/gitthings/waydroid_script/stuff/gapps.py", line 170, in copy_13
    shutil.copy2(src_file_path, dst_file_path)
  File "/usr/lib/python3.12/shutil.py", line 475, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.12/shutil.py", line 273, in copyfile
    _fastcopy_sendfile(fsrc, fdst)
  File "/usr/lib/python3.12/shutil.py", line 164, in _fastcopy_sendfile
    raise err from None
  File "/usr/lib/python3.12/shutil.py", line 150, in _fastcopy_sendfile
    sent = os.sendfile(outfd, infd, offset, blocksize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 28] No space left on device: '/tmp/gapps/extract/system/product/priv-app/Phonesky/Phonesky.apk' -> '/tmp/waydroid/system/product/priv-app/Phonesky/Phonesky.apk'

**Comment by NiffirgkcaJ** [comment]
I'm having issues with GAPPS also! I cannot install it on my Arch-based distro. :(

`INFO: Downloading gapps.zip now to /home/petpfne/.cache/waydroid-script/downloads/gapps.zip .....
INFO: Extracting /home/petpfne/.cache/waydroid-script/downloads/gapps.zip to /tmp/gapps/extract
    Processing app package : /tmp/gapps/extract/Core/backuprestore-all.tar.lz
ERROR: tar (child): lzip: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

Traceback (most recent call last):
  File "/home/petpfne/waydroid_script/main.py", line 358, in <module>
    main()
  File "/home/petpfne/waydroid_script/main.py", line 354, in main
    interact()
  File "/home/petpfne/waydroid_script/main.py", line 256, in interact
    install_app(args)
  File "/home/petpfne/waydroid_script/main.py", line 113, in install_app
    item.install()
  File "/home/petpfne/waydroid_script/stuff/general.py", line 177, in install
    self.copy()
  File "/home/petpfne/waydroid_script/stuff/gapps.py", line 109, in copy
    return self.copy_11()
           ^^^^^^^^^^^^^^
  File "/home/petpfne/waydroid_script/stuff/gapps.py", line 126, in copy_11
    run(["tar", "--lzip", "-xvf", os.path.join(self.extract_to, "Core",
  File "/home/petpfne/waydroid_script/tools/helper.py", line 48, in run
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['tar', '--lzip', '-xvf', '/tmp/gapps/extract/Core/backuprestore-all.tar.lz', '-C', '/tmp/gapps/extract/appunpack']' returned non-zero exit status 2.`

**Comment by NiffirgkcaJ** [comment]
I'm having issues with GAPPS also! I cannot install it on my Arch-based distro. :(

```INFO: Downloading gapps.zip now to /home/petpfne/.cache/waydroid-script/downloads/gapps.zip .....
INFO: Extracting /home/petpfne/.cache/waydroid-script/downloads/gapps.zip to /tmp/gapps/extract
    Processing app package : /tmp/gapps/extract/Core/backuprestore-all.tar.lz
ERROR: tar (child): lzip: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

Traceback (most recent call last):
  File "/home/petpfne/waydroid_script/main.py", line 358, in <module>
    main()
  File "/home/petpfne/waydroid_script/main.py", line 354, in main
    interact()
  File "/home/petpfne/waydroid_script/main.py", line 256, in interact
    install_app(args)
  File "/home/petpfne/waydroid_script/main.py", line 113, in install_app
    item.install()
  File "/home/petpfne/waydroid_script/stuff/general.py", line 177, in install
    self.copy()
  File "/home/petpfne/waydroid_script/stuff/gapps.py", line 109, in copy
    return self.copy_11()
           ^^^^^^^^^^^^^^
  File "/home/petpfne/waydroid_script/stuff/gapps.py", line 126, in copy_11
    run(["tar", "--lzip", "-xvf", os.path.join(self.extract_to, "Core",
  File "/home/petpfne/waydroid_script/tools/helper.py", line 48, in run
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['tar', '--lzip', '-xvf', '/tmp/gapps/extract/Core/backuprestore-all.tar.lz', '-C', '/tmp/gapps/extract/appunpack']' returned non-zero exit status 2.
