### ISSUE TITLE
Get Android ID for device registration fails

### ISSUE THREAD

**Issue by YackyYam** [casualsnek/waydroid_script#20]
```
adam@mobian:~/Downloads/waydroid_script$ sudo python3 waydroid_extras.py -i
Traceback (most recent call last):
  File "/home/adam/Downloads/waydroid_script/waydroid_extras.py", line 573, in <module>
    main()
  File "/home/adam/Downloads/waydroid_script/waydroid_extras.py", line 566, in main
    get_android_id()
  File "/home/adam/Downloads/waydroid_script/waydroid_extras.py", line 183, in get_android_id
    queryout = subprocess.check_output(["sqlite3", "/var/lib/waydroid/data/data/com.google.android.gsf/databases/gservices.db", sqs.strip()], stderr=subprocess.STDOUT)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sqlite3'
```

After installing sqlite3 script ran fine.  User README needs updated to add sqlite3 as a requirement.

**Comment by casualsnek** [comment]
Thank you, I will add sqlite as requirement !
