### ISSUE TITLE
e2fsck error - returned non-zero exit status 0

### ISSUE THREAD

**Issue by iFuckEggs** [casualsnek/waydroid_script#202]
Been battling this for a while now. 
I can not for the life of me get widevine installed. I get this error every time no matter what I try. 

`INFO: Resizing /var/lib/waydroid/images/vendor.img to 825M
ERROR: e2fsck 1.47.2-rc1 (28-Nov-2024)

Traceback (most recent call last):
  File "/home/cannar/waydroid_script/main.py", line 358, in <module>
    main()
  File "/home/cannar/waydroid_script/main.py", line 351, in main
    args.func(args)
  File "/home/cannar/waydroid_script/main.py", line 107, in install_app
    resize("vendor")
  File "/home/cannar/waydroid_script/main.py", line 50, in resize
    images.resize(img, new_size)
  File "/home/cannar/waydroid_script/tools/images.py", line 27, in resize
    run(["sudo", "e2fsck", "-y", "-f", img_file], ignore="^e2fsck \d+\.\d+\.\d (.+)\n$")
/home/cannar/waydroid_script/tools/images.py:1: SyntaxWarning: invalid escape sequence '\d'
  import configparser
  File "/home/cannar/waydroid_script/tools/helper.py", line 48, in run
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['sudo', 'e2fsck', '-y', '-f', '/var/lib/waydroid/images/vendor.img']' returned non-zero exit status 0.
`
I've tried running `sudo e2fsck -y -f /var/lib/waydroid/images/vendor.img
` separately but it does nothing, the img isn't resized. 

Curiously, if I completely reset my install the script will go all the way through with no errors, but widevine doesn't get installed.

**Comment by YogSottot** [comment]
But the script doesn't edit the image for a long time. It uses overlayfs. Apparently you have a very old version of the script or an old waydroid without overlayfs support.

```
ls -la /var/lib/waydroid/overlay/vendor/bin/hw/
total 20
drwxr-xr-x 2 root root 4096 июн  7  2023 .
drwxr-xr-x 3 root root 4096 июн  7  2023 ..
-rwxrwxrwx 1 root 2000 9296 июн  7  2023 android.hardware.drm@1.3-service-lazy.widevine
```

**Comment by iFuckEggs** [comment]
> But the script doesn't edit the image for a long time. It uses overlayfs. Apparently you have a very old version of the script or an old waydroid without overlayfs support.
> 
> ```
> ls -la /var/lib/waydroid/overlay/vendor/bin/hw/
> total 20
> drwxr-xr-x 2 root root 4096 июн  7  2023 .
> drwxr-xr-x 3 root root 4096 июн  7  2023 ..
> -rwxrwxrwx 1 root 2000 9296 июн  7  2023 android.hardware.drm@1.3-service-lazy.widevine
> ```

Interesting. 
The script I cloned into using the readme on the main page, and waydroid is also the latest straight from their servers. 
android.hardware.drm@1.1-service.widevine is present in the overlay/vendor folder but doesn't seem to work..
