### ISSUE TITLE
error on arch linux

### ISSUE THREAD

**Issue by Greasy-Monkey** [casualsnek/waydroid_script#25]
system info:
```
❯ uname -a
Linux lenovo 5.15.12-arch1-1 #1 SMP PREEMPT Wed, 29 Dec 2021 12:04:56 +0000 x86_64 GNU/Linux
```
```
❯ sudo python3 waydroid_extras.py -g
==> Stopping waydroid and unmounting already mounted images...
==> Excepted hash: 55db1a79b1d41573d7c2cd5927189779  | File hash: 
==> Found system image: /usr/share/waydroid-extra/images/system.img
==> Resizing system image....
==> Unmounting .. 
==> Warning: umount failed.. umount: /tmp/waydroidimage: no mount point specified.
 
==> OpenGapps zip not downloaded or hash mismatches, downloading now .....
100%|█████████████████████████████████████████████████████████████████████| 111M/111M [00:59<00:00, 1.84MiB/s]
==> Extracting opengapps...
==> Processing app package : /tmp/ogapps/extract/Core/backuprestore-all.tar.lz
tar (child): lzip: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Traceback (most recent call last):
  File "/home/xxx/Github/waydroid_script/waydroid_extras.py", line 573, in <module>
    main()
  File "/home/xxx/Github/waydroid_script/waydroid_extras.py", line 561, in main
    install_gapps()
  File "/home/xxx/Github/waydroid_script/waydroid_extras.py", line 153, in install_gapps
    app_name = os.listdir(os.path.join(extract_to, "appunpack"))[0]
IndexError: list index out of range
. . .

**Comment by Greasy-Monkey** [comment]
aah sorry , fixed lzip was not installed
