### ISSUE TITLE
Can't use proxy

### ISSUE THREAD

**Issue by cnjhb** [casualsnek/waydroid_script#34]
command used
`waydroid-extras -l`
output
```
==> Found system image: /usr/share/waydroid-extra/images/system.img
==> Resizing system image....
==> Failed to resize image '/usr/share/waydroid-extra/images/system.img' .. !  e2fsck 1.46.5 (30-Dec-2021)
/usr/share/waydroid-extra/images/system.img is mounted.
e2fsck: Cannot continue, aborting.



==> You can exit and retry with sudo or force continue (May fail installation !), Continue ? [y/N]: y
==> Unmounting .. 
==> libhoudini zip not downloaded or hash mismatches, downloading now .....
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 994, in _prepare_proxy
    conn.connect()
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 364, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 501, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "/usr/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "/usr/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "/usr/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /casualsnek/miscpackages/main/libhoudini_a11.zip (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/waydroid-extras", line 597, in <module>
    main()
  File "/usr/bin/waydroid-extras", line 594, in main
    install_houdini()
  File "/usr/bin/waydroid-extras", line 365, in install_houdini
    loc_md5 = download_file(houdini_zip_url, dl_file_name)
  File "/usr/bin/waydroid-extras", line 37, in download_file
    response = requests.get(url,stream=True)
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /casualsnek/miscpackages/main/libhoudini_a11.zip (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

```
proxy
```
export http_proxy=http://127.0.0.1:8889
export https_proxy=https://127.0.0.1:8889
```
system:archlinux

**Comment by CnTeng** [comment]
You can edit the code. the download_file function line 32
like this:
```
def download_file(url, f_name):
    proxies = {
      "http": "http://127.0.0.1:10809",
      "https": "http://127.0.0.1:10809",
    }
    md5 = ""
    response = requests.get(url, stream=True, proxies=proxies)
```

**Comment by aspects19** [comment]
The new script has no download function and hence I cant use a proxy. Can someone assist me
