### ISSUE TITLE
Fail to install libhoudini on Fedora.

### ISSUE THREAD

**Issue by laichiaheng** [casualsnek/waydroid_script#48]
```
[laichiaheng@julian-pc waydroid_script-main]$ LANG=C sudo python3 waydroid_extras.py -l
/home/laichiaheng/.cache/waydroid_script/downloads
==> Found system image: /var/lib/waydroid/images/system.img
==> Resizing system image....
==> Failed to resize image '/var/lib/waydroid/images/system.img' .. !  resize2fs 1.46.5 (30-Dec-2021)
resize2fs: Read-only file system While checking for on-line resizing support
Filesystem at /var/lib/waydroid/images/system.img is mounted on /var/lib/waydroid/rootfs; on-line resizing required
old_desc_blocks = 1, new_desc_blocks = 1

==> You can exit and retry with sudo or force continue (May fail installation !), Continue ? [y/N]: y
==> Unmounting .. 
==> Extracting archive...
==> Chmodding...
==> Copying library files ...
Traceback (most recent call last):
  File "/home/laichiaheng/下載/waydroid_script-main/waydroid_extras.py", line 594, in <module>
    main()
  File "/home/laichiaheng/下載/waydroid_script-main/waydroid_extras.py", line 591, in main
    install_houdini()
  File "/home/laichiaheng/下載/waydroid_script-main/waydroid_extras.py", line 376, in install_houdini
    shutil.copytree(os.path.join(extract_to, "system"), os.path.join(sys_image_mount, "system"), dirs_exist_ok=True)
  File "/usr/lib64/python3.10/shutil.py", line 558, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/lib64/python3.10/shutil.py", line 512, in _copytree
    raise Error(errors)
shutil.Error: [('/tmp/houdiniunpack/system/lib64/libhoudini.so', '/tmp/waydroidimage/system/lib64/libhoudini.so', "[Errno 30] Read-only file system: '/tmp/waydroidimage/system/lib64/libhoudini.so'"), ('/tmp/houdiniunpack/system/lib64/arm64', '/tmp/waydroidimage/system/lib64/arm64', "[Errno 30] Read-only file system: '/tmp/waydroidimage/system/lib64/arm64'"), (<DirEntry 'lib64'>, '/tmp/waydroidimage/system/lib64', '[Errno 30] Read-only file system'), ('/tmp/houdiniunpack/system/lib/arm', '/tmp/waydroidimage/system/lib/arm', "[Errno 30] Read-only file system: '/tmp/waydroidimage/system/lib/arm'"), ('/tmp/houdiniunpack/system/lib/libhoudini.so', '/tmp/waydroidimage/system/lib/libhoudini.so', "[Errno 30] Read-only file system: '/tmp/waydroidimage/system/lib/libhoudini.so'"), (<DirEntry 'lib'>, '/tmp/waydroidimage/system/lib', '[Errno 30] Read-only file system'), ('/tmp/houdiniunpack/system/bin/houdini64', '/tmp/waydroidimage/system/bin/houdini64', "[Errno 30] Read-only file system: '/tmp/waydroidimage/system/bin/houdini64'"), ('/tmp/houdiniunpack/system/bin/arm', '/tmp/waydroidimage/system/bin/arm', "[Errno 30] Read-only file system: '/tmp/waydroidimage/system/bin/arm'"), ('/tmp/houdiniunpack/system/bin/houdini', '/tmp/waydroidimage/system/bin/houdini', "[Errno 30] Read-only file system: '/tmp/waydroidimage/system/bin/houdini'"), ('/tmp/houdiniunpack/system/bin/arm64', '/tmp/waydroidimage/system/bin/arm64', "[Errno 30] Read-only file system: '/tmp/waydroidimage/system/bin/arm64'"), (<DirEntry 'bin'>, '/tmp/waydroidimage/system/bin', '[Errno 30] Read-only file system'), ('/tmp/houdiniunpack/system', '/tmp/waydroidimage/system', '[Errno 30] Read-only file system')]
```

**Comment by skinatro** [comment]
i think this is because they removed ashmem but i am not sure

**Comment by laichiaheng** [comment]
It works perfectly on Arch Linux.
