### ISSUE TITLE
read-only filesystem error when trying to install Magisk

### ISSUE THREAD

**Issue by cobalt2727** [casualsnek/waydroid_script#58]
tl;dr is in the title, console output below:

```bash
cobalt@ideapad-flex-5:~/waydroid_script$ sudo python3 waydroid_extras.py -m
/home/cobalt/.cache/waydroid_script/downloads
==> Found system image: /var/lib/waydroid/images/system.img
==> Resizing system image....
==> Failed to resize image '/var/lib/waydroid/images/system.img' .. !  resize2fs 1.46.5 (30-Dec-2021)
resize2fs: Read-only file system While checking for on-line resizing support
Filesystem at /var/lib/waydroid/images/system.img is mounted on /var/lib/waydroid/rootfs; on-line resizing required
old_desc_blocks = 1, new_desc_blocks = 1

==> You can exit and retry with sudo or force continue (May fail installation !), Continue ? [y/N]: y
==> Unmounting .. 
==> Extracting archive...
==> Installing magisk now ...
Traceback (most recent call last):
  File "/home/cobalt/waydroid_script/waydroid_extras.py", line 594, in <module>
    main()
  File "/home/cobalt/waydroid_script/waydroid_extras.py", line 589, in main
    install_magisk()
  File "/home/cobalt/waydroid_script/waydroid_extras.py", line 501, in install_magisk
    with open(os.path.join(sys_image_mount, "system", "bin", "init-magisk.sh"), "w") as imf:
OSError: [Errno 30] Read-only file system: '/tmp/waydroidimage/system/bin/init-magisk.sh'
```

This is running on Pop!_OS 22.04

**Comment by EvilBoi123** [comment]
yeah also happen to me in Archlinux

**Comment by ayasa520** [comment]
I think it's fine if you just reboot.
Second, the script to install magisk doesn't work for the latest waydroid image. You can check out this fork https://github.com/LegacyGamerHD/waydroid_script

**Comment by cobalt2727** [comment]
will there be a PR to this repo later?

**Comment by Gentran** [comment]
Try run e2fsck on system.img before running the script.

**Comment by ayasa520** [comment]
> I think it's fine if you just reboot. Second, the script to install magisk doesn't work for the latest waydroid image. You can check out this fork https://github.com/LegacyGamerHD/waydroid_script

I think this repo is no longer maintained.  Anyway this fork I mentioned is working. https://github.com/LegacyGamerHD/waydroid_script/pull/2#issuecomment-1352636617

**Comment by casualsnek** [comment]
> > will there be a PR to this repo later?
> 
> I think this repo is no longer maintained. Anyway this fork I mentioned is working. [LegacyGamerHD#2 (comment)](https://github.com/LegacyGamerHD/waydroid_script/pull/2#issuecomment-1352636617)

I will still accept PR(s) after checking, the repo is not too active as i no longer mess around with waydroid, i will start working on cleaning up code and try to update stuffs asap !
