### ISSUE TITLE
Attempting to install apps fails when mounting `system.img`.

### ISSUE THREAD

**Issue by ImperatorStorm** [casualsnek/waydroid_script#90]
Running `sudo waydroid-extras install <app>` fails on attempting to mount `system.img` as read+write.
Using commit 59547e774335c12f08d20b65490bb1be840d7f87.
Log:
```
% sudo waydroid-extras install gapps libndk widevine magisk
INFO: Resizing /var/lib/waydroid/images/system.img to 4830M
INFO: Resizing /var/lib/waydroid/images/vendor.img to 2474M
INFO: Mounting /var/lib/waydroid/images/system.img to /tmp/waydroid
WARN: /tmp/waydroid is not a mount point
ERROR: mount: /tmp/waydroid: WARNING: source write-protected, mounted read-only.

Traceback (most recent call last):
  File "/usr/bin/waydroid-extras", line 344, in <module>
    main()
  File "/usr/bin/waydroid-extras", line 337, in main
    args.func(args)
  File "/usr/bin/waydroid-extras", line 104, in install_app
    mount("system", copy_dir)
  File "/usr/bin/waydroid-extras", line 41, in mount
    images.mount(img, mount_point)
  File "/opt/waydroid-script/tools/images.py", line 12, in mount
    run(["mount", "-o", "rw", image, mount_point])
  File "/opt/waydroid-script/tools/helper.py", line 47, in run
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['mount', '-o', 'rw', '/var/lib/waydroid/images/system.img', '/tmp/waydroid']' returned non-zero exit status 0.
```
Note: `waydroid-extras` is the name given to `main.py` by [waydroid-script-git](https://aur.archlinux.org/packages/waydroid-script-git) on the AUR.

**Comment by ayasa520** [comment]
try ` sudo umount /usr/share/waydroid-extra/images/{system,vendor}.img`  or ` sudo umount /var/lib/waydroid/images/{system,vendor}.img ` and run it again.

**Comment by ImperatorStorm** [comment]
```
% sudo umount /var/lib/waydroid/images/{system,vendor}.img
umount: /var/lib/waydroid/images/system.img: not mounted.
umount: /var/lib/waydroid/images/vendor.img: not mounted.
```

**Comment by ImperatorStorm** [comment]
Hmm, resetting waydroid seems to have fixed this, not sure how I broke it on my end.
Closing.
